#!/usr/bin/env node

var rw = require("rw");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    lineParser = rw.lineParser(),
    lineNumber = 0,
    oddWriter = rw.fileWriter("split-odd.out"),
    evenWriter = rw.fileWriter("split-even.out");

reader.fill(function pipe(error) {
  if (error) throw error;
  var data = reader.read(),
      line;

  if (data) lineParser.push(data);

  while ((line = lineParser.pop(reader.ended)) != null) {
    var writer = ++lineNumber & 1 ? oddWriter : evenWriter;
    if (!writer.write(line + "\n")) {
      return writer.drain(pipe);
    }
  }

  if (reader.ended) return oddWriter.end(), evenWriter.end();

  reader.fill(pipe);
});
